/** Timeout budgets for Codex app-server operations and their HAPI callers. */
export const CODEX_INTERACTIVE_REQUEST_TIMEOUT_MS = 20_000
export const CODEX_STEER_TURN_LOOKUP_TIMEOUT_MS = 5_000
export const CODEX_RESUME_LAYER_HEADROOM_MS = 2 * 60_000
export const CODEX_HISTORY_REQUEST_TIMEOUT_MS = 61 * 60_000
export const CODEX_RESUME_WEBHOOK_TIMEOUT_MS = CODEX_HISTORY_REQUEST_TIMEOUT_MS + CODEX_RESUME_LAYER_HEADROOM_MS
export const CODEX_RESUME_RPC_TIMEOUT_MS = CODEX_RESUME_WEBHOOK_TIMEOUT_MS + CODEX_RESUME_LAYER_HEADROOM_MS
